### ISSUE TITLE
Can `let_it_be` and `before_all` be used in the same example group?

### ISSUE THREAD

**Issue by agrberg** [palkan/test-prof#56]
```ruby
RSpec.describe Object do
  let_it_be(:foo) { 'this is foo' }
  
  before_all { @bar = 'this is bar' }

  it 'does something' do
    @foo #=> nil
    @bar #=> nil
    foo #=> 'this is foo'
    bar #=> NameError: undefined local variable or method 'bar'
  end
end
```

If I remove the `let_it_be` then the `before_all` runs. In the test `@bar #=> this is bar` and of course `foo #=> NameError for 'foo'`.

**Comment by palkan** [comment]
Yep, it is possible to use both simultaneously. Even more – `let_it_be` uses `before_all` internally.

I've just tried the snippet and my output is:

```
@foo #=> nil
@bar #=> "this is bar"
foo #=> "this is foo"
bar #=> NameError: undefined local variable or method 'bar'
```

And that's the expected behaviour. Do you have other hooks in your test? I can't see any reason for `@bar` to be `nil`.
In this case `before_all` is equal to `before(:all)`.

`@foo` is `nil`, because `let_it_be` doesn't add this instance variable, it behaves like `let!`.

`bar` is undefined, because, well, we haven't defined it.

**Comment by agrberg** [comment]
I though `let_it_be` would use `before_all` internally but without the ivars. Thanks for confirming that.

I'm sorry for the confusion. I found the problem. I was on version 0.3.0 and once I upgraded to 0.4.6 I can confirm that they are both working.

**Comment by Jefferson-Faseler** [comment]
For anyone else having this issue I had the same problem and upgrading solved it for me as well.
