### ISSUE TITLE
Using threads appears to confuse `before_all`.

### ISSUE THREAD

**Issue by RobKeep** [palkan/test-prof#69]
### Tell us about your environment

**Ruby Version:** 
2.4.2

**Framework Version (RSpec, Minitest, FactoryGirl, Rails, whatever):**
rspec: 3.7
rails: 5.0.7

**TestProf Version:**
0.4.9

### What did you do?
I added a test to make sure concurrent updates were not triggering a race condition, which involved multiple simultaneous threads.

### What did you expect to happen?
The test would pass or fail on its own merits.

### What actually happened?
The tested passed, but I also got this error at the end of an unrelated test in a different file:
```
An error occurred in an `after(:context)` hook.
Failure/Error: transaction.rollback

NoMethodError:
  undefined method `rollback' for nil:NilClass
# /Users/robert/.rvm/gems/ruby-2.4.2@backoffice/gems/test-prof-0.4.9/lib/test_prof/recipes/rspec/before_all.rb:24:in `block in before_all'
```

Adding `if ActiveRecord::Base.connection.open_transactions > 0` to the end of the offending line makes the error go away.  I don't understand enough of what's going on to say if that's the correct fix or if that's just masking a different issue.

**Comment by palkan** [comment]
Hi @RobKeep!

Thanks for the report.

>  I don't understand enough of what's going on to say if that's the correct fix or if that's just masking a different issue.

The problem is that ActiveRecord uses a connection per-thread, so all threads except the main one are not able to access the data created with the `before_all` (since it's wrapping multiple examples into a transaction).

So, I don't think it's possible to test concurrent scenarios with transaction tests at all.

Note: since Rails 5.1 ActiveRecord uses the same connection for all the threads in `test` environment. But that means that all the queries are made sequentially, there could not be concurrent updates; as I understand, your test scenario won't be able to reveal race conditions in that case too.

**Comment by RobKeep** [comment]
Thanks for the quick response @palkan!  Threading was useful for proving that we had in fact fixed our concurrency issue.  Going forward we'll probably move it to a black box approach (external selenium driven test) to keep an artifact around that makes sure we haven't re-introduced a race condition.

I suppose this issue can be closed, given that there's not really anything to be done on your side.

**Comment by palkan** [comment]
> given that there's not really anything to be done on your side.

Yep( ¯\_(ツ)_/¯
